### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by MartGon** [MartGon/BlockBuster#2]
# TODO

## Development
- [x] GL Texture Object Wrapper
- [x] Code Reorganization
- [ ] Collisions Tests

## GitHub Actions

- [x] Build
- [x] Run Tests
- [x] Valgrind
- [ ] Send Discord/Telegram message on fail

## Libraries

- [x] Tests - Doctest
- [x] Texture loading - stbi
- [x] Graphics - OpenGL and glad
- [x] Math - GLM
- [x] GUI - ImGui
- [ ] Scripts - Lua, sol3
- [ ] Networking - SDL_Net, enet
